# Generated by Django 3.0.8 on 2020-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('logs', models.CharField(max_length=100)),
                ('veneers', models.CharField(max_length=100)),
                ('decking', models.CharField(max_length=100)),
                ('boards', models.CharField(max_length=100)),
                ('flooring', models.CharField(max_length=100)),
                ('skirtings', models.CharField(max_length=100)),
            ],
        ),
    ]
