# Generated by Django 3.0.8 on 2020-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtimber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirymodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='boards',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='business',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='decking',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='flooring',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='logs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='skirtings',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='veneers',
            field=models.CharField(max_length=200),
        ),
    ]
